BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `exercises` (
	`muscle_group`	TEXT,
	`field2`	TEXT,
	`exercise`	TEXT
);
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Full Reverse Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Incline Hip Thrust');
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Incline Reverse Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Lying Hip Thrust');
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Reverse Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Lower','Reverse Medicine Ball Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Alternating Heel Touch');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Bent-Knee Medicine Ball Hip Rotation');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Cable Chop');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Cross Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Cross Crunch w/ Medicine Ball');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Decline Cross Sit-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Decline Sit-Up w/ Twist');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Reverse Cable Chop');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Seated Medicine Ball Twist');
INSERT INTO `exercises` VALUES ('Abdominals','Obliques','Trunk Rotator');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Front Plank (from knees)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Front Plank (from toes)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Front Plank (tripod - 1 arm and 2 legs or 2 legs and 1 arm)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Side-Plank (from knees)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Side-Plank (hip lift)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Side-Plank (from toes)');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Ab Cycle');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Kneeling Ab Rollout');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Medicine Ball V-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Total','V-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Total','Weighted V-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Bent Knee Sit-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Bent-Knee Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Decline Crunch');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Decline Sit-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Heel Touch');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Sit-Up');
INSERT INTO `exercises` VALUES ('Abdominals','Upper','Weighted Crunch');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Assisted Pull-Up');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Close-Grip Lat Pulldown');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Inverted Pull-Up');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Lat Pulldown');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Pull-Up');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Reverse-Grip Lat Pullown');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Reverse-Grip Pull-Up');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','V-Bar Pull-Up');
INSERT INTO `exercises` VALUES ('Back','Latissimus Dorsi','Wide-Grip Lat Pulldown');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Alternating Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Barbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Hammer Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Long Barbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Reverse-Grip Barbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Bent-Over Single-Arm Long Barbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Machine Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','One Arm Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Reverse Incline Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Rope Cable Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Seated Cable Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Seated Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Single-Arm Cable Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Single-Arm Dumbbell Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Single-Arm Lat Pulldown');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Standing Cable Row');
INSERT INTO `exercises` VALUES ('Back','Lat.Dorsi/Rhomboids','Standing Single-Arm Cable Row');
INSERT INTO `exercises` VALUES ('Biceps','','Alternating Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Alternating Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Barbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Bicep Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Bottom/Top/Full Curls');
INSERT INTO `exercises` VALUES ('Biceps','','Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Concentration Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Cross Body Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','EZ-Bar Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Incline Alternating Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Incline Alternating Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Incline Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Incline Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Kneeling Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Lying Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Lying Double Biceps Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Lying High Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Machine Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Overhead Double Biceps Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Overhead Rope Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher Barbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher EZ-Bar Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher Hammer Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Preacher Single-Arm Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Reverse Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Rope Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Seated Alternating Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Seated Alternating Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Seated Dumbbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Seated Hammer Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Single-Arm Barbell Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Single-Arm Cable Curl');
INSERT INTO `exercises` VALUES ('Biceps','','Single-Arm Dumbbell Curl w/ Incline Bench');
INSERT INTO `exercises` VALUES ('Biceps','','Spider Curl');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Barbell Calf Raise');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Calf Press');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Calf Raise - Seated');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Calf Raise - Standing');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Dumbbell Calf Raise');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Single-Leg Calf Press');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Single-Leg Dumbbell Calf Raise');
INSERT INTO `exercises` VALUES ('Calves','Gastrocnemius','Smith Machine Calf Raise');
INSERT INTO `exercises` VALUES ('Calves','Soleus','Seated Calf Raise');
INSERT INTO `exercises` VALUES ('Calves','Soleus','Seated Single-Leg Calf Raise');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Alternating Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Barbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Chest Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Decline Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Decline Smith Machine Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Dumbbell Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Elevated Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Flat Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Alternating Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Barbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Hammer Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Single-Arm Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Smith Machine Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Twisting Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Kneeling Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Machine Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Machine Vertical Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Medicine Ball Crossover Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Single-Arm Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Smith Machine Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Twisting Dumbbell Bench Press');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Wide-Grip Push-Up');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Cable Crossover');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Cable Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Decline Dumbbell Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Dumbbell Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','High Cable Crossover');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Cable Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Dumbbell Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Incline Twisting Dumbbell Fly');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Low Cable Crossover');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Pec Deck');
INSERT INTO `exercises` VALUES ('Chest','Pectoralis','Pec Deck Fly');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Bent-Knee Single-Leg Hip Lift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Elevated Hip Lift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Elevated Single-Leg Hip Lift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Hip Lift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Single-Leg Hip Lift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Deadlift');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Leg Curl');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Lying Alternating Leg Curl');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Lying Leg Curl');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Lying Single-Leg Curl');
INSERT INTO `exercises` VALUES ('Legs','Hamstrings','Seated Leg Curl');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Diagonal Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Hack Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Reverse Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Side Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Split Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Step-Up');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Barbell Walking Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Diagonal Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Diagonal Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Reverse Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Side Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Split Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Step-Up');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Dumbbell Walking Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Forward Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lateral Barbell Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lateral Barbell Step-Up');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lateral Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lateral Step-Up');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Leg Press');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Lying Machine Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Machine Hack Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Reverse Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Arm Barbell Side Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Arm Dumbbell Side Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Barbell Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Box Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Dumbbell Box Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Dumbbell Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Smith Machine Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Split Squat');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Step-Up');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Walking Lunge');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Alternating Leg Extension');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Leg Extension');
INSERT INTO `exercises` VALUES ('Legs','Quadriceps','Single-Leg Extension');
INSERT INTO `exercises` VALUES ('Lower Back','Erector Spinae','Alternating Superman');
INSERT INTO `exercises` VALUES ('Lower Back','Erector Spinae','Back Raise');
INSERT INTO `exercises` VALUES ('Lower Back','Erector Spinae','Quadruped Alternating Superman');
INSERT INTO `exercises` VALUES ('Lower Back','Erector Spinae','Superman');
INSERT INTO `exercises` VALUES ('Lower Back','Erector Spinae','Superman Hold');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Arnold Dumbbell Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Barbell Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Dumbbell Alternating Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Dumbbell Front Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Dumbbell Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Dumbbell Twisting Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Machine Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Seated Dumbbell Rear Delt Elbow Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Single-Arm Dumbbell Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Smith Machine Shoulder Press');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Barbell Front Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Bent-Over Cable Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Bent-Over Dumbbell Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Cable Front Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Cable Lateral Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Dumbbell Lateral Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Front Plate Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Kneeling Single-Arm Cable Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Lying Dumbbell External Rotation');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Lying Dumbbell Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Lying Single-Arm Dumbbell Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Pec Deck Real Delt Extensions');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Reverse Incline Dumbbell Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Seated Dumbbell Rear Delt Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Delts/Traps','Single-Arm Cable Lateral Raise');
INSERT INTO `exercises` VALUES ('Shoulders','Rotator Cuff','Cable External Rotation');
INSERT INTO `exercises` VALUES ('Triceps','','Close-Grip Bench Press');
INSERT INTO `exercises` VALUES ('Triceps','','Forward Lean Dips');
INSERT INTO `exercises` VALUES ('Triceps','','Assisted Dips');
INSERT INTO `exercises` VALUES ('Triceps','','Bench Dips');
INSERT INTO `exercises` VALUES ('Triceps','','Diamond Push-Up');
INSERT INTO `exercises` VALUES ('Triceps','','Dips');
INSERT INTO `exercises` VALUES ('Triceps','','Machine Dips');
INSERT INTO `exercises` VALUES ('Triceps','','Decline Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Decline EZ-Bar Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Decline Single Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Decline Single-Arm Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Dumbbell Kickback');
INSERT INTO `exercises` VALUES ('Triceps','','Incline EZ-Bar Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Kneeling Cable Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Leaning Overhead Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Low Cable Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Cable Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying EZ-Bar Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Overhead EZ-Bar Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Reverse EZ-Bar Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Single Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Single-Arm Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Lying Tricep Extensions');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead Dumbbell Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead EZ-Bar Triceps Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead Rope Cable Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead Single Dumbbell Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead Single-Arm Cable Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Overhead Single-Arm Dumbbell Tricep Extension');
INSERT INTO `exercises` VALUES ('Triceps','','Reverse Tricep Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Rope Triceps Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Single-Arm Towel Triceps Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Single-Arm Triceps Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Towel Triceps Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Tricep Extensions');
INSERT INTO `exercises` VALUES ('Triceps','','Tricep Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','Tricep Pushdown');
INSERT INTO `exercises` VALUES ('Triceps','','V-Bar Tricep Pushdown');
COMMIT;
